### ISSUE TITLE
macos brew issue: manticoresearch: SHA256 mismatch

### ISSUE THREAD

**Issue by madgreen1** [manticoresoftware/homebrew-tap#101]
Hi.
I have a problem with upgrading from c 6.0 to 6.2.
brew issues:
==> Downloading https://repo.manticoresearch.com/repository/manticoresearch_macos/release/manticore-6.2.12-230822-dc5144d35-osx11.6-x86_64-main.tar.gz
Error: manticoresearch: SHA256 mismatch
Expected: 826e7a486835bfc97dc5c8d7c4bd2afa582141cd64f68cc4f18b43924c2f9e22
  Actual: 2ef10a29a440d2d792eef5295f3c681ff2bd85106c278733db615629819a8bc6

and
==> Downloading https://repo.manticoresearch.com/repository/manticoresearch_macos/release/manticore-columnar-lib-2.2.4-230822-5aec342-osx11.6-x86_64.tar.gz
Error: manticore-extra: SHA256 mismatch
Expected: c26c557b1359cd79862ead962b33f3910e7bca4d85344c99fa58ae34d1947dbb
  Actual: 2cbd0b7eb846208253f245ede729a42961f61d6a85adcbd78236c54f16ed0291

**Comment by sanikolaev** [comment]
Please try brew cleanup

**Comment by madgreen1** [comment]
This is the first thing I tried :)

**Comment by sanikolaev** [comment]
I've fixed it. Pls try again. You may need to update the tap.

**Comment by madgreen1** [comment]
manticoresearch is ok now, but manticore-extra: SHA256 mismatch

**Comment by sanikolaev** [comment]
> manticoresearch is ok now, but manticore-extra: SHA256 mismatch

Fixed too.

**Comment by madgreen1** [comment]
Thanks!
