### ISSUE TITLE
manticoresearch build fails after moving tag 5.0.3 to another commit

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/homebrew-tap#40]
Subj. fails here https://github.com/manticoresoftware/homebrew-manticore/actions/runs/3798244877/jobs/6498950109#step:8:63 like this:

>   Error: stable sha256 changed without the url/version also changing; please create an issue upstream to rule out malicious circumstances and to find out why the file changed.

Jon re-run doesn't help.

The task is to research why it's happening and decide what's the best way to fix it.

**Comment by githubmanticore** [comment]
➤ Don Hardman commented:
 

 
I changed how we will update versions in the future and appended them to the version date and commit. That will solve the issue and make it possible to do often updates.  
 
The pull request is here – https://github.com/manticoresoftware/homebrew-manticore/pull/42

**Comment by githubmanticore** [comment]
➤ Don Hardman commented:
 

 
The pull request is here – https://github.com/manticoresoftware/homebrew-manticore/pull/42 
It's succeeded before, and I just squashed and forced push it. We can wait until it finishes to add the `pr-pull` tag to merge if it's ok.

**Comment by githubmanticore** [comment]
➤ Sergey Nikolaev commented:
 

 
All done.
