### ISSUE TITLE
Unable to install or update manticoresearch rel 6.2.0 via homebrew under macos

### ISSUE THREAD

**Issue by ghost** [manticoresoftware/homebrew-tap#96]
We're seeing an error "Could not find versions by using provided URL and pattern", when installing, updating or cleaning up packages (manticore or otherwise) via homebrew. It seems there's a bug with the versioning/linking of manticore's latest release as the issue resolves itself as soon as manticoresearch and its components are uninstalled:

`➜  ~ brew install manticoresoftware/tap/manticoresearch manticoresoftware/tap/manticore-extra

==> Downloading https://formulae.brew.sh/api/formula.jws.json
#################################################################################################################################################################################### 100.0%
==> Fetching dependencies for manticoresoftware/tap/manticoresearch: manticoresoftware/tap/manticore-backup, manticoresoftware/tap/manticore-buddy and manticoresoftware/tap/manticore-icudata
==> Fetching manticoresoftware/tap/manticore-backup
==> Downloading file:///private/tmp/d20230805-71378-7yv9ly/manticore-backup.tar.gz
#################################################################################################################################################################################### 100.0%
==> Fetching manticoresoftware/tap/manticore-buddy
==> Downloading file:///private/tmp/d20230805-71378-1ta08kj/manticore-buddy.tar.gz
#################################################################################################################################################################################### 100.0%
==> Fetching manticoresoftware/tap/manticore-icudata
==> Downloading file:///private/tmp/d20230805-71378-ppioe/manticore-icudata.tar.gz
#################################################################################################################################################################################### 100.0%
==> Fetching manticoresoftware/tap/manticoresearch
==> Downloading file:///private/tmp/d20230805-71378-1n216cr/manticoresearch.tar.gz
#################################################################################################################################################################################### 100.0%
Error: Could not find versions by using provided URL and pattern`

`➜  ~ brew info manticoresoftware/tap/manticoresearch
==> manticoresoftware/tap/manticoresearch: stable 6.2.0-230804-45680f95d
Open source database for search
https://manticoresearch.com
Conflicts with:
  sphinx (because Manticore Search is a fork of Sphinxsearch)
Not installed
From: https://github.com/manticoresoftware/homebrew-tap/blob/HEAD/Formula/manticoresearch.rb
License: GPL-2.0
==> Dependencies
Required: libpq ✔, mysql-client ✔, openssl@1.1 ✔, unixodbc ✔, zstd ✔
Recommended: manticoresoftware/tap/manticore-backup ✘, manticoresoftware/tap/manticore-buddy ✘, manticoresoftware/tap/manticore-icudata ✘
==> Options
--without-manticore-backup
	Build without manticore-backup support
--without-manticore-buddy
	Build without manticore-buddy support
--without-manticore-icudata
	Build without manticore-icudata support
==> Caveats
If you're facing an issue with "too many open files", you may need to adjust your
system's maxfiles limit. You can do this by executing the following command:

sudo launchctl limit maxfiles 16384 65536

Bear in mind, this will only establish the limit for the duration of your current
login session. If you want this adjustment to be permanent, you'll need to modify
your system's launchd configuration.

To restart manticoresoftware/tap/manticoresearch after an upgrade:
  brew services restart manticoresoftware/tap/manticoresearch
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/manticoresearch/bin/searchd --config /usr/local/etc/manticoresearch/manticore.conf --nodetach
==> Analytics
install: 52 (30 days), 166 (90 days), 221 (365 days)
install-on-request: 52 (30 days), 166 (90 days), 221 (365 days)
build-error: 1 (30 days)`

`HOMEBREW_VERSION: 4.1.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 128df14e0afd0525564051a7665708c2973a3cab
Last commit: 5 days ago
Core tap JSON: 05 Aug 03:48 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 24
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 24-core 64-bit westmere
Clang: 14.0.0 build 1400
Git: 2.41.0 => /usr/local/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 12.6.8-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: 14.2`

**Comment by sanikolaev** [comment]
Should be fixed now. There was a problem with x86_64 based macs.
Feel free to reopen in case it's not.
