### ISSUE TITLE
brew services / brew search manticore very slow

### ISSUE THREAD

**Issue by cevin** [manticoresoftware/homebrew-tap#97]
<img width="996" alt="image" src="https://github.com/manticoresoftware/homebrew-tap/assets/338110/e65ed7cb-174a-4218-a270-f247530083eb">

All other operations are fast, once manticore is involved the brew operations are very slow.

**Comment by cevin** [comment]
`brew services list`

`brew update`

`brew search manticore`

**Comment by cevin** [comment]
<img width="586" alt="image" src="https://github.com/manticoresoftware/homebrew-tap/assets/338110/80bcae7d-1ac9-4ee2-875b-bd630cd5a4ec">

**Comment by cyformatician** [comment]
You can hear the crickets in here ... @sanikolaev 

I'm experiencing the same issue, with manticore installed via homebrew. Executing any brew command causes an outbound connection to repo.manticoresearch.com ... As soon as manticore is uninstalled, brew executes normally and way faster.

![Screen Shot 2023-10-25 at 3 02 25 PM](https://github.com/manticoresoftware/homebrew-tap/assets/141473993/de610ef2-9877-4733-aa18-c8a7c8f52765)

**Comment by sanikolaev** [comment]
Sorry for the delay folks. We'll look into this issue this week.

**Comment by sanikolaev** [comment]
Should work fine after you update the tap.
The dev formulas that scan repo.manticoresearch.com to find the freshest packages have been moved to https://github.com/manticoresoftware/homebrew-tap-dev

Feel free to reopen in case there's still any issue.
